{% set version = "0.4.2" %}
{% set sha256 = "541616df177e13f914fca2f749c64f723d7b83c8ea9096509c9f318676ea91da" %}

package:
  name: pymeasure
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ralph-group/pymeasure/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.6.1
    - pandas >=0.14
    - pyvisa >=1.8
    - pyserial >=2.7
    - pyqt 4.11.*

test:
  imports:
    - pymeasure

about:
  home: https://github.com/ralph-group/pymeasure
  license: MIT
  summary: Scientific measurement library for instruments, experiments, and live-plotting.
  description: |
    PyMeasure makes scientific measurements easy to set up and run. The package contains a 
    repository of instrument classes and a system for running experiment procedures, 
    which provides graphical interfaces for graphing live data and managing queues of 
    experiments. Both parts of the package are independent, and when combined provide 
    all the necessary requirements for advanced measurements with only limited coding.
  doc_url: http://pymeasure.readthedocs.io
  dev_url: https://github.com/ralph-group/pymeasure

extra:
  recipe-maintainers:
    - melund
    - ddale
    - cjermain

